name = "redirect31"
main = "_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]
workers_dev = true
routes = [

  { pattern = "hu.xinquins.dpdns.org", custom_domain = true },
  { pattern = "xinquins.dpdns.org", custom_domain = true },
  { pattern = "api24-normal.tiktokv.com.xinquins.dpdns.org", custom_domain = true },
  { pattern = "support.zoom.us.hu.xinquins.dpdns.org", custom_domain = true },
  { pattern = "api24-normal.tiktokv.com.hu.xinquins.dpdns.org", custom_domain = true },
  { pattern = "collection.linefriends.com.hu.xinquins.dpdns.org", custom_domain = true },
  { pattern = "ava.game.naver.com.hu.xinquins.dpdns.org", custom_domain = true },
  { pattern = "df.game.naver.com.hu.xinquins.dpdns.org", custom_domain = true },
  { pattern = "onering:hu.xinquins.dpdns.org", custom_domain = true },

]

[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true
